@ErpFactory.Api_HostAddress = http://localhost:5101
@JwtToken = paste-token-here

POST {{ErpFactory.Api_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password123"
}

###

GET {{ErpFactory.Api_HostAddress}}/api/Customers
Accept: application/json
Authorization: Bearer {{JwtToken}}

###
